### ISSUE TITLE
CGI::Ex 2.44 lost some commits

### ISSUE THREAD

**Issue by chazmcgarvey** [ljepson/CGI-Ex#6]
Hey Lonny,

The following commits were all inexplicably reverted -- at the same time -- in 0098f507ec2f093c13d2e0df86c682fc5de893a8 and so are not in the latest release:

c6d58cd94f1263529f325eaf4109659f613c663c - Bumping the version of CGI::Ex to 2.43 and adding info to the changelog
49ae68dffd4a09666973ad3a5ee0b8e2a284b89d - Allow HTML5 input types to be filled 
2d1f4aee09d0aee26d820ba7c25dffc78b8b7c59 - Silence warning about CGI::param in list context
1677670f16e98014f911a117c7d646c037af502a - Fix bug preventing logging out if bouncing

It looks like the 2.43 version bump revert was at least later restored somewhat in 60bc0b97767ccd6caccc11afd815f9ca70e53281, but the others are still missing.

I'm guessing it was unintentional because the history looks a little confused. :smile: If it was purposeful, though, let me know what the problems are and I'll fix them. My apps rely on those commits, so I can't upgrade to CGI::Ex 2.44.

**Comment by ljepson** [comment]
I'll get it taken care of. My apologies!

**Comment by chazmcgarvey** [comment]
Cool. Thanks Lonny. :)

**Comment by chazmcgarvey** [comment]
Closing because these are back in master.
